export const COUNTRY_REGIONS: Record<string, string> = {
  'Afghanistan': 'Asia',
  'Albania': 'Europe',
  'Algeria': 'Africa',
  'Angola': 'Africa',
  'Argentina': 'South America',
  'Armenia': 'Asia',
  'Australia': 'Oceania',
  'Austria': 'Europe',
  'Azerbaijan': 'Asia',
  'Bangladesh': 'Asia',
  'Belarus': 'Europe',
  'Belgium': 'Europe',
  'Benin': 'Africa',
  'Bhutan': 'Asia',
  'Bolivia': 'South America',
  'Bosnia & Herz.': 'Europe',
  'Botswana': 'Africa',
  'Brazil': 'South America',
  'Brunei': 'Asia',
  'Bulgaria': 'Europe',
  'Burkina Faso': 'Africa',
  'Burundi': 'Africa',
  'Cambodia': 'Asia',
  'Cameroon': 'Africa',
  'Canada': 'North America',
  'C.A.R.': 'Africa',
  'Chad': 'Africa',
  'Chile': 'South America',
  'China': 'Asia',
  'Colombia': 'South America',
  'Congo': 'Africa',
  'DRC': 'Africa',
  'Costa Rica': 'North America',
  'Croatia': 'Europe',
  'Cuba': 'North America',
  'Cyprus': 'Europe',
  'Czechia': 'Europe',
  'Denmark': 'Europe',
  'Djibouti': 'Africa',
  'Dom. Rep.': 'North America',
  'Ecuador': 'South America',
  'Egypt': 'Africa',
  'El Salvador': 'North America',
  'Eq. Guinea': 'Africa',
  'Eritrea': 'Africa',
  'Estonia': 'Europe',
  'Ethiopia': 'Africa',
  'Falkland Is.': 'South America',
  'Fiji': 'Oceania',
  'Finland': 'Europe',
  'France': 'Europe',
  'Gabon': 'Africa',
  'Gambia': 'Africa',
  'Georgia': 'Asia',
  'Germany': 'Europe',
  'Ghana': 'Africa',
  'Greece': 'Europe',
  'Greenland': 'North America',
  'Guatemala': 'North America',
  'Guinea': 'Africa',
  'Guinea-Bissau': 'Africa',
  'Guyana': 'South America',
  'Haiti': 'North America',
  'Honduras': 'North America',
  'Hungary': 'Europe',
  'Iceland': 'Europe',
  'India': 'Asia',
  'Indonesia': 'Asia',
  'Iran': 'Asia',
  'Iraq': 'Asia',
  'Ireland': 'Europe',
  'Israel': 'Asia',
  'Italy': 'Europe',
  "Côte d'Ivoire": 'Africa',
  'Jamaica': 'North America',
  'Japan': 'Asia',
  'Jordan': 'Asia',
  'Kazakhstan': 'Asia',
  'Kenya': 'Africa',
  'N. Korea': 'Asia',
  'S. Korea': 'Asia',
  'Kuwait': 'Asia',
  'Kyrgyzstan': 'Asia',
  'Laos': 'Asia',
  'Latvia': 'Europe',
  'Lebanon': 'Asia',
  'Lesotho': 'Africa',
  'Liberia': 'Africa',
  'Libya': 'Africa',
  'Lithuania': 'Europe',
  'Luxembourg': 'Europe',
  'N. Macedonia': 'Europe',
  'Madagascar': 'Africa',
  'Malawi': 'Africa',
  'Malaysia': 'Asia',
  'Mali': 'Africa',
  'Mauritania': 'Africa',
  'Mexico': 'North America',
  'Moldova': 'Europe',
  'Mongolia': 'Asia',
  'Montenegro': 'Europe',
  'Morocco': 'Africa',
  'Mozambique': 'Africa',
  'Myanmar': 'Asia',
  'Namibia': 'Africa',
  'Nepal': 'Asia',
  'Netherlands': 'Europe',
  'New Caledonia': 'Oceania',
  'New Zealand': 'Oceania',
  'Nicaragua': 'North America',
  'Niger': 'Africa',
  'Nigeria': 'Africa',
  'Norway': 'Europe',
  'Oman': 'Asia',
  'Pakistan': 'Asia',
  'Panama': 'North America',
  'Papua N.G.': 'Oceania',
  'Paraguay': 'South America',
  'Peru': 'South America',
  'Philippines': 'Asia',
  'Poland': 'Europe',
  'Portugal': 'Europe',
  'Puerto Rico': 'North America',
  'Qatar': 'Asia',
  'Romania': 'Europe',
  'Russia': 'Europe',
  'Rwanda': 'Africa',
  'Saudi Arabia': 'Asia',
  'Senegal': 'Africa',
  'Serbia': 'Europe',
  'Sierra Leone': 'Africa',
  'Slovakia': 'Europe',
  'Slovenia': 'Europe',
  'Somalia': 'Africa',
  'South Africa': 'Africa',
  'S. Sudan': 'Africa',
  'Spain': 'Europe',
  'Sri Lanka': 'Asia',
  'Sudan': 'Africa',
  'Suriname': 'South America',
  'eSwatini': 'Africa',
  'Sweden': 'Europe',
  'Switzerland': 'Europe',
  'Syria': 'Asia',
  'Taiwan': 'Asia',
  'Tajikistan': 'Asia',
  'Tanzania': 'Africa',
  'Thailand': 'Asia',
  'Timor-Leste': 'Asia',
  'Togo': 'Africa',
  'Trinidad & T.': 'North America',
  'Tunisia': 'Africa',
  'Turkey': 'Asia',
  'Turkmenistan': 'Asia',
  'Uganda': 'Africa',
  'Ukraine': 'Europe',
  'UAE': 'Asia',
  'UK': 'Europe',
  'USA': 'North America',
  'Uruguay': 'South America',
  'Uzbekistan': 'Asia',
  'Venezuela': 'South America',
  'Vietnam': 'Asia',
  'Yemen': 'Asia',
  'Zambia': 'Africa',
  'Zimbabwe': 'Africa',
  'Antarctica': 'Antarctica',
  'N. Cyprus': 'Europe',
  'Palestine': 'Asia',
  'W. Sahara': 'Africa',
  'Solomon Is.': 'Oceania',
  'Vanuatu': 'Oceania',
  'Tonga': 'Oceania',
  'Samoa': 'Oceania',
}
