import { countryAlpha2 } from '@/lib/country-flags'

const COUNTRY_IANA: Record<string, string[]> = {
  AF: ['Asia/Kabul'],
  AL: ['Europe/Tirane'],
  DZ: ['Africa/Algiers'],
  AO: ['Africa/Luanda'],
  AR: ['America/Argentina/Buenos_Aires'],
  AM: ['Asia/Yerevan'],
  AU: ['Australia/Perth', 'Australia/Adelaide', 'Australia/Sydney'],
  AT: ['Europe/Vienna'],
  AZ: ['Asia/Baku'],
  BD: ['Asia/Dhaka'],
  BY: ['Europe/Minsk'],
  BE: ['Europe/Brussels'],
  BJ: ['Africa/Porto-Novo'],
  BT: ['Asia/Thimphu'],
  BO: ['America/La_Paz'],
  BA: ['Europe/Sarajevo'],
  BW: ['Africa/Gaborone'],
  BR: ['America/Manaus', 'America/Sao_Paulo'],
  BN: ['Asia/Brunei'],
  BG: ['Europe/Sofia'],
  BF: ['Africa/Ouagadougou'],
  BI: ['Africa/Bujumbura'],
  KH: ['Asia/Phnom_Penh'],
  CM: ['Africa/Douala'],
  CA: ['America/Vancouver', 'America/Edmonton', 'America/Winnipeg', 'America/Toronto', 'America/Halifax'],
  CF: ['Africa/Bangui'],
  TD: ['Africa/Ndjamena'],
  CL: ['America/Santiago'],
  CN: ['Asia/Shanghai'],
  CO: ['America/Bogota'],
  CG: ['Africa/Brazzaville'],
  CD: ['Africa/Kinshasa', 'Africa/Lubumbashi'],
  CR: ['America/Costa_Rica'],
  HR: ['Europe/Zagreb'],
  CU: ['America/Havana'],
  CY: ['Asia/Nicosia'],
  CZ: ['Europe/Prague'],
  DK: ['Europe/Copenhagen'],
  DJ: ['Africa/Djibouti'],
  DO: ['America/Santo_Domingo'],
  EC: ['America/Guayaquil'],
  EG: ['Africa/Cairo'],
  SV: ['America/El_Salvador'],
  GQ: ['Africa/Malabo'],
  ER: ['Africa/Asmara'],
  EE: ['Europe/Tallinn'],
  ET: ['Africa/Addis_Ababa'],
  FK: ['Atlantic/Stanley'],
  FJ: ['Pacific/Fiji'],
  FI: ['Europe/Helsinki'],
  FR: ['Europe/Paris'],
  GA: ['Africa/Libreville'],
  GM: ['Africa/Banjul'],
  GE: ['Asia/Tbilisi'],
  DE: ['Europe/Berlin'],
  GH: ['Africa/Accra'],
  GR: ['Europe/Athens'],
  GL: ['America/Nuuk', 'America/Scoresbysund'],
  GT: ['America/Guatemala'],
  GN: ['Africa/Conakry'],
  GW: ['Africa/Bissau'],
  GY: ['America/Guyana'],
  HT: ['America/Port-au-Prince'],
  HN: ['America/Tegucigalpa'],
  HK: ['Asia/Hong_Kong'],
  HU: ['Europe/Budapest'],
  IS: ['Atlantic/Reykjavik'],
  IN: ['Asia/Kolkata'],
  ID: ['Asia/Jakarta', 'Asia/Makassar', 'Asia/Jayapura'],
  IR: ['Asia/Tehran'],
  IQ: ['Asia/Baghdad'],
  IE: ['Europe/Dublin'],
  IL: ['Asia/Jerusalem'],
  IT: ['Europe/Rome'],
  CI: ['Africa/Abidjan'],
  JM: ['America/Jamaica'],
  JP: ['Asia/Tokyo'],
  JO: ['Asia/Amman'],
  KZ: ['Asia/Almaty', 'Asia/Aqtau'],
  KE: ['Africa/Nairobi'],
  KP: ['Asia/Pyongyang'],
  KR: ['Asia/Seoul'],
  KW: ['Asia/Kuwait'],
  KG: ['Asia/Bishkek'],
  LA: ['Asia/Vientiane'],
  LV: ['Europe/Riga'],
  LB: ['Asia/Beirut'],
  LS: ['Africa/Maseru'],
  LR: ['Africa/Monrovia'],
  LY: ['Africa/Tripoli'],
  LT: ['Europe/Vilnius'],
  LU: ['Europe/Luxembourg'],
  MK: ['Europe/Skopje'],
  MG: ['Indian/Antananarivo'],
  MW: ['Africa/Blantyre'],
  MY: ['Asia/Kuala_Lumpur'],
  ML: ['Africa/Bamako'],
  MR: ['Africa/Nouakchott'],
  MX: ['America/Tijuana', 'America/Chihuahua', 'America/Mexico_City'],
  MD: ['Europe/Chisinau'],
  MN: ['Asia/Hovd', 'Asia/Ulaanbaatar'],
  ME: ['Europe/Podgorica'],
  MA: ['Africa/Casablanca'],
  MZ: ['Africa/Maputo'],
  MM: ['Asia/Yangon'],
  NA: ['Africa/Windhoek'],
  NP: ['Asia/Kathmandu'],
  NL: ['Europe/Amsterdam'],
  NC: ['Pacific/Noumea'],
  NZ: ['Pacific/Auckland'],
  NI: ['America/Managua'],
  NE: ['Africa/Niamey'],
  NG: ['Africa/Lagos'],
  NO: ['Europe/Oslo'],
  OM: ['Asia/Muscat'],
  PK: ['Asia/Karachi'],
  PA: ['America/Panama'],
  PG: ['Pacific/Port_Moresby'],
  PY: ['America/Asuncion'],
  PE: ['America/Lima'],
  PH: ['Asia/Manila'],
  PL: ['Europe/Warsaw'],
  PT: ['Europe/Lisbon'],
  PR: ['America/Puerto_Rico'],
  QA: ['Asia/Qatar'],
  RO: ['Europe/Bucharest'],
  RU: ['Europe/Kaliningrad', 'Europe/Moscow', 'Asia/Yekaterinburg', 'Asia/Novosibirsk', 'Asia/Vladivostok', 'Asia/Kamchatka'],
  RW: ['Africa/Kigali'],
  SA: ['Asia/Riyadh'],
  SN: ['Africa/Dakar'],
  RS: ['Europe/Belgrade'],
  SL: ['Africa/Freetown'],
  SG: ['Asia/Singapore'],
  SK: ['Europe/Bratislava'],
  SI: ['Europe/Ljubljana'],
  SO: ['Africa/Mogadishu'],
  ZA: ['Africa/Johannesburg'],
  SS: ['Africa/Juba'],
  ES: ['Atlantic/Canary', 'Europe/Madrid'],
  LK: ['Asia/Colombo'],
  SD: ['Africa/Khartoum'],
  SR: ['America/Paramaribo'],
  SZ: ['Africa/Mbabane'],
  SE: ['Europe/Stockholm'],
  CH: ['Europe/Zurich'],
  SY: ['Asia/Damascus'],
  TW: ['Asia/Taipei'],
  TJ: ['Asia/Dushanbe'],
  TZ: ['Africa/Dar_es_Salaam'],
  TH: ['Asia/Bangkok'],
  TL: ['Asia/Dili'],
  TG: ['Africa/Lome'],
  TT: ['America/Port_of_Spain'],
  TN: ['Africa/Tunis'],
  TR: ['Europe/Istanbul'],
  TM: ['Asia/Ashgabat'],
  UG: ['Africa/Kampala'],
  UA: ['Europe/Kyiv'],
  AE: ['Asia/Dubai'],
  GB: ['Europe/London'],
  US: ['America/Anchorage', 'America/Los_Angeles', 'America/Denver', 'America/Chicago', 'America/New_York'],
  UY: ['America/Montevideo'],
  UZ: ['Asia/Tashkent'],
  VE: ['America/Caracas'],
  VN: ['Asia/Ho_Chi_Minh'],
  YE: ['Asia/Aden'],
  ZM: ['Africa/Lusaka'],
  ZW: ['Africa/Harare'],
  AQ: ['Antarctica/McMurdo'],
  PS: ['Asia/Hebron'],
  EH: ['Africa/El_Aaiun'],
  SB: ['Pacific/Guadalcanal'],
  VU: ['Pacific/Efate'],
  TO: ['Pacific/Tongatapu'],
  WS: ['Pacific/Apia'],
  AD: ['Europe/Andorra'],
  BH: ['Asia/Bahrain'],
  BB: ['America/Barbados'],
  BS: ['America/Nassau'],
  BZ: ['America/Belize'],
  CV: ['Atlantic/Cape_Verde'],
  KM: ['Indian/Comoro'],
  DM: ['America/Dominica'],
  GD: ['America/Grenada'],
  KI: ['Pacific/Tarawa', 'Pacific/Kiritimati'],
  XK: ['Europe/Belgrade'],
  LI: ['Europe/Vaduz'],
  MO: ['Asia/Macau'],
  MV: ['Indian/Maldives'],
  MT: ['Europe/Malta'],
  MH: ['Pacific/Majuro'],
  MU: ['Indian/Mauritius'],
  FM: ['Pacific/Pohnpei'],
  MC: ['Europe/Monaco'],
  NR: ['Pacific/Nauru'],
  PW: ['Pacific/Palau'],
  SM: ['Europe/San_Marino'],
  SC: ['Indian/Mahe'],
  LC: ['America/St_Lucia'],
  KN: ['America/St_Kitts'],
  AG: ['America/Antigua'],
  TV: ['Pacific/Funafuti'],
  VA: ['Europe/Vatican'],
}

const MAX_DISPLAY = 3

const fmt = new Intl.DateTimeFormat('en-GB', {
  hour: '2-digit',
  minute: '2-digit',
  hour12: false,
})

function formatIana(tz: string): string {
  try {
    const f = new Intl.DateTimeFormat('en-GB', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: false,
      timeZone: tz,
    })
    return f.format(new Date())
  } catch {
    return ''
  }
}

export function getCountryTimezones(country: string | null | undefined): string[] {
  const code = countryAlpha2(country)
  if (!code) return []
  return COUNTRY_IANA[code] ?? []
}

export function formatCountryTimesDisplay(country: string | null | undefined): string {
  const zones = getCountryTimezones(country)
  if (zones.length === 0) return ''
  const times = zones.map(formatIana).filter(Boolean)
  const unique = [...new Set(times)]
  if (unique.length <= MAX_DISPLAY) return unique.join(', ')
  return unique.slice(0, MAX_DISPLAY).join(', ') + ` +${unique.length - MAX_DISPLAY}`
}

export function formatContactTime(timezone: string | null | undefined): string {
  if (!timezone) return ''
  if (timezone.startsWith('UTC')) {
    const m = timezone.match(/UTC([+-])(\d{2}):(\d{2})/)
    if (!m) return ''
    const sign = m[1] === '+' ? 1 : -1
    const minutes = sign * (parseInt(m[2]) * 60 + parseInt(m[3]))
    const now = new Date()
    const utcMs = now.getTime() + now.getTimezoneOffset() * 60000
    return fmt.format(new Date(utcMs + minutes * 60000))
  }
  return formatIana(timezone)
}
