import { drizzle } from 'drizzle-orm/node-postgres'
import { Pool } from 'pg'
import * as schema from '../lib/db/schema'

const pool = new Pool({ connectionString: process.env.DATABASE_URL! })
const db = drizzle(pool, { schema })

const USER_ID = 'demo@konterra.app'

const contactIds = {
  alex: crypto.randomUUID(),
  maria: crypto.randomUUID(),
  yuki: crypto.randomUUID(),
  omar: crypto.randomUUID(),
  sofia: crypto.randomUUID(),
  james: crypto.randomUUID(),
  lena: crypto.randomUUID(),
  raj: crypto.randomUUID(),
  chen: crypto.randomUUID(),
  fatima: crypto.randomUUID(),
  marco: crypto.randomUUID(),
  anna: crypto.randomUUID(),
}

function daysAgo(n: number) {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d
}

function futureDate(n: number) {
  const d = new Date()
  d.setDate(d.getDate() + n)
  return d
}

async function seed() {
  await db.insert(schema.users).values({
    id: USER_ID,
    email: USER_ID,
    name: 'Demo User',
  }).onConflictDoNothing()

  await db.insert(schema.contacts).values([
    {
      id: contactIds.alex,
      userId: USER_ID,
      name: 'Alex Turner',
      company: 'Stripe',
      role: 'Engineering Manager',
      city: 'San Francisco',
      country: 'United States',
      lat: 37.7749,
      lng: -122.4194,
      email: 'alex.turner@stripe.com',
      phone: '+1-415-555-0101',
      linkedin: 'alexturner',
      twitter: 'alexturner_sf',
      telegram: 'alexturner',
      tags: ['tech', 'fintech', 'investor'],
      notes: 'Met at Stripe Sessions 2024. Very sharp on payments infra. Interested in collab on developer tools.',
      rating: 5,
      gender: 'male' as const,
      relationshipType: 'business' as const,
      metAt: 'Stripe Sessions 2024',
      metDate: new Date('2024-05-15'),
      lastContactedAt: daysAgo(3),
      nextFollowUp: futureDate(7),
      communicationStyle: 'direct' as const,
      preferredChannel: 'email' as const,
      responseSpeed: 'same-day' as const,
      timezone: 'America/Los_Angeles',
      language: 'English',
      birthday: new Date('1990-03-15'),
      personalInterests: ['climbing', 'craft beer', 'sci-fi'],
      professionalGoals: ['VP Engineering by 2026', 'launch developer platform'],
      painPoints: ['hiring senior engineers', 'cross-team alignment'],
      influenceLevel: 8,
      networkReach: 9,
      trustLevel: 4,
      loyaltyIndicator: 'proven' as const,
      financialCapacity: 'funded' as const,
      motivations: ['career growth', 'technical excellence'],
    },
    {
      id: contactIds.maria,
      userId: USER_ID,
      name: 'Maria Santos',
      company: 'Sequoia Capital',
      role: 'Partner',
      city: 'Menlo Park',
      country: 'United States',
      lat: 37.4530,
      lng: -122.1817,
      email: 'maria@sequoiacap.com',
      linkedin: 'mariasantos',
      tags: ['vc', 'investor', 'ai'],
      notes: 'Key VC contact. Invested in 3 unicorns last year. Warm intro through Alex.',
      rating: 5,
      gender: 'female' as const,
      relationshipType: 'business' as const,
      metAt: 'TechCrunch Disrupt 2024',
      metDate: new Date('2024-10-20'),
      lastContactedAt: daysAgo(12),
      nextFollowUp: futureDate(3),
      communicationStyle: 'analytical' as const,
      preferredChannel: 'linkedin' as const,
      responseSpeed: 'slow' as const,
      timezone: 'America/Los_Angeles',
      language: 'English',
      birthday: new Date('1985-07-22'),
      personalInterests: ['wine', 'art collecting', 'marathon'],
      professionalGoals: ['find next 10x company', 'AI infrastructure thesis'],
      painPoints: ['deal flow quality', 'founder due diligence'],
      influenceLevel: 10,
      networkReach: 10,
      trustLevel: 3,
      loyaltyIndicator: 'likely' as const,
      financialCapacity: 'institutional' as const,
      motivations: ['returns', 'market insight'],
    },
    {
      id: contactIds.yuki,
      userId: USER_ID,
      name: 'Yuki Tanaka',
      company: 'Sony',
      role: 'Product Director',
      city: 'Tokyo',
      country: 'Japan',
      lat: 35.6762,
      lng: 139.6503,
      email: 'yuki.tanaka@sony.co.jp',
      telegram: 'yuki_tokyo',
      tags: ['gaming', 'hardware', 'japan'],
      notes: 'Runs PlayStation VR division. Potential partner for spatial computing projects.',
      rating: 4,
      gender: 'female' as const,
      relationshipType: 'business' as const,
      metAt: 'Tokyo Game Show 2024',
      metDate: new Date('2024-09-26'),
      lastContactedAt: daysAgo(45),
      nextFollowUp: daysAgo(5),
      communicationStyle: 'diplomatic' as const,
      preferredChannel: 'email' as const,
      responseSpeed: 'same-day' as const,
      timezone: 'Asia/Tokyo',
      language: 'Japanese',
      birthday: new Date('1988-12-03'),
      personalInterests: ['anime', 'calligraphy', 'hiking'],
      professionalGoals: ['expand VR ecosystem', 'western partnerships'],
      painPoints: ['localization speed', 'developer onboarding'],
      influenceLevel: 7,
      networkReach: 6,
      trustLevel: 4,
      loyaltyIndicator: 'proven' as const,
      financialCapacity: 'institutional' as const,
      motivations: ['innovation', 'market expansion'],
    },
    {
      id: contactIds.omar,
      userId: USER_ID,
      name: 'Omar Al-Rashid',
      company: 'Careem',
      role: 'CTO',
      city: 'Dubai',
      country: 'United Arab Emirates',
      lat: 25.2048,
      lng: 55.2708,
      email: 'omar@careem.com',
      twitter: 'omar_tech',
      tags: ['mobility', 'mena', 'leadership'],
      notes: 'Super connector in MENA tech. Can open doors to Dubai investment scene.',
      rating: 4,
      gender: 'male' as const,
      relationshipType: 'business' as const,
      metAt: 'GITEX 2024',
      metDate: new Date('2024-10-14'),
      lastContactedAt: daysAgo(20),
      communicationStyle: 'expressive' as const,
      preferredChannel: 'call' as const,
      responseSpeed: 'immediate' as const,
      timezone: 'Asia/Dubai',
      language: 'Arabic',
      birthday: new Date('1987-05-10'),
      personalInterests: ['motorsport', 'architecture', 'coffee'],
      professionalGoals: ['IPO preparation', 'AI-driven operations'],
      painPoints: ['talent retention', 'regulatory complexity'],
      influenceLevel: 8,
      networkReach: 8,
      trustLevel: 3,
      loyaltyIndicator: 'likely' as const,
      financialCapacity: 'funded' as const,
      motivations: ['regional leadership', 'scaling'],
    },
    {
      id: contactIds.sofia,
      userId: USER_ID,
      name: 'Sofia Petrov',
      company: 'DeepMind',
      role: 'Research Scientist',
      city: 'London',
      country: 'United Kingdom',
      lat: 51.5074,
      lng: -0.1278,
      email: 'sofia.petrov@deepmind.com',
      github: 'sofiapetrov',
      tags: ['ai', 'research', 'ml'],
      notes: 'Published 12 papers on transformer architectures. Brilliant mind, introvert. Prefers async communication.',
      rating: 4,
      gender: 'female' as const,
      relationshipType: 'business' as const,
      metAt: 'NeurIPS 2024',
      metDate: new Date('2024-12-10'),
      lastContactedAt: daysAgo(8),
      communicationStyle: 'analytical' as const,
      preferredChannel: 'email' as const,
      responseSpeed: 'slow' as const,
      timezone: 'Europe/London',
      language: 'English',
      personalInterests: ['chess', 'classical music', 'philosophy'],
      professionalGoals: ['publish on reasoning models', 'build AGI safety framework'],
      painPoints: ['compute budget', 'publication pressure'],
      influenceLevel: 6,
      networkReach: 5,
      trustLevel: 4,
      loyaltyIndicator: 'proven' as const,
      financialCapacity: 'bootstrapper' as const,
      motivations: ['intellectual curiosity', 'impact'],
    },
    {
      id: contactIds.james,
      userId: USER_ID,
      name: 'James Okonkwo',
      company: 'Flutterwave',
      role: 'CEO',
      city: 'Lagos',
      country: 'Nigeria',
      lat: 6.5244,
      lng: 3.3792,
      email: 'james@flutterwave.com',
      twitter: 'jamesokonkwo',
      tags: ['fintech', 'africa', 'ceo'],
      notes: 'Building the Stripe of Africa. Massive energy. Needs intros to EU regulators.',
      rating: 5,
      gender: 'male' as const,
      relationshipType: 'business' as const,
      metAt: 'AfricArena 2024',
      metDate: new Date('2024-11-08'),
      lastContactedAt: daysAgo(2),
      nextFollowUp: futureDate(14),
      communicationStyle: 'expressive' as const,
      preferredChannel: 'call' as const,
      responseSpeed: 'immediate' as const,
      timezone: 'Africa/Lagos',
      language: 'English',
      birthday: new Date('1991-08-20'),
      personalInterests: ['basketball', 'afrobeats', 'real estate'],
      professionalGoals: ['expand to 20 African countries', 'Series D'],
      painPoints: ['compliance across borders', 'currency volatility'],
      influenceLevel: 9,
      networkReach: 8,
      trustLevel: 5,
      loyaltyIndicator: 'proven' as const,
      financialCapacity: 'funded' as const,
      motivations: ['pan-African vision', 'financial inclusion'],
    },
    {
      id: contactIds.lena,
      userId: USER_ID,
      name: 'Lena Mayer',
      company: 'BMW',
      role: 'Head of Digital',
      city: 'Munich',
      country: 'Germany',
      lat: 48.1351,
      lng: 11.5820,
      email: 'lena.mayer@bmw.de',
      linkedin: 'lenamayer',
      tags: ['automotive', 'digital', 'enterprise'],
      notes: 'Driving BMW digital transformation. Old friend from university. Very reliable.',
      rating: 4,
      gender: 'female' as const,
      relationshipType: 'friend' as const,
      metAt: 'TU Munich',
      metDate: new Date('2012-09-01'),
      lastContactedAt: daysAgo(60),
      communicationStyle: 'direct' as const,
      preferredChannel: 'text' as const,
      responseSpeed: 'same-day' as const,
      timezone: 'Europe/Berlin',
      language: 'German',
      birthday: new Date('1990-02-14'),
      personalInterests: ['skiing', 'photography', 'cooking'],
      professionalGoals: ['CDO position', 'launch connected car platform'],
      painPoints: ['legacy systems', 'board buy-in for digital'],
      influenceLevel: 7,
      networkReach: 6,
      trustLevel: 5,
      loyaltyIndicator: 'proven' as const,
      financialCapacity: 'institutional' as const,
      motivations: ['innovation within tradition', 'sustainability'],
    },
    {
      id: contactIds.raj,
      userId: USER_ID,
      name: 'Raj Patel',
      company: 'Freshworks',
      role: 'VP Sales',
      city: 'Bangalore',
      country: 'India',
      lat: 12.9716,
      lng: 77.5946,
      email: 'raj.patel@freshworks.com',
      telegram: 'rajpatel_blr',
      tags: ['saas', 'sales', 'india'],
      notes: 'Knows every SaaS founder in India. Great at intros. Owes me a favor from the Zoho deal.',
      rating: 3,
      gender: 'male' as const,
      relationshipType: 'business' as const,
      metAt: 'SaaStr Annual 2023',
      metDate: new Date('2023-09-12'),
      lastContactedAt: daysAgo(90),
      communicationStyle: 'expressive' as const,
      preferredChannel: 'call' as const,
      responseSpeed: 'same-day' as const,
      timezone: 'Asia/Kolkata',
      language: 'Hindi',
      personalInterests: ['cricket', 'bollywood', 'meditation'],
      professionalGoals: ['crack US enterprise market', 'build partner network'],
      painPoints: ['US brand perception', 'enterprise sales cycle length'],
      influenceLevel: 6,
      networkReach: 7,
      trustLevel: 3,
      loyaltyIndicator: 'neutral' as const,
      financialCapacity: 'funded' as const,
      motivations: ['revenue growth', 'market validation'],
    },
    {
      id: contactIds.chen,
      userId: USER_ID,
      name: 'Chen Wei',
      company: 'ByteDance',
      role: 'Staff Engineer',
      city: 'Beijing',
      country: 'China',
      lat: 39.9042,
      lng: 116.4074,
      email: 'chen.wei@bytedance.com',
      github: 'chenwei',
      tags: ['tech', 'china', 'infrastructure'],
      notes: 'Core architect of TikTok recommendation engine. Rarely available but incredibly valuable conversations.',
      rating: 4,
      gender: 'male' as const,
      relationshipType: 'business' as const,
      metAt: 'KubeCon 2023',
      metDate: new Date('2023-11-07'),
      lastContactedAt: daysAgo(120),
      communicationStyle: 'analytical' as const,
      preferredChannel: 'email' as const,
      responseSpeed: 'slow' as const,
      timezone: 'Asia/Shanghai',
      language: 'Mandarin',
      personalInterests: ['go (weiqi)', 'poetry', 'running'],
      professionalGoals: ['open source contributions', 'distributed systems research'],
      painPoints: ['geopolitical restrictions', 'work-life balance'],
      influenceLevel: 5,
      networkReach: 4,
      trustLevel: 3,
      loyaltyIndicator: 'neutral' as const,
      financialCapacity: 'bootstrapper' as const,
      motivations: ['technical mastery', 'open source'],
    },
    {
      id: contactIds.fatima,
      userId: USER_ID,
      name: 'Fatima Hassan',
      company: 'WHO',
      role: 'Digital Health Advisor',
      city: 'Geneva',
      country: 'Switzerland',
      lat: 46.2044,
      lng: 6.1432,
      email: 'hassanf@who.int',
      tags: ['health', 'ngo', 'policy'],
      notes: 'Key contact for health-tech projects. Connected to UN innovation network.',
      rating: 3,
      gender: 'female' as const,
      relationshipType: 'business' as const,
      metAt: 'Web Summit 2024',
      metDate: new Date('2024-11-12'),
      lastContactedAt: daysAgo(30),
      communicationStyle: 'diplomatic' as const,
      preferredChannel: 'email' as const,
      responseSpeed: 'slow' as const,
      timezone: 'Europe/Zurich',
      language: 'French',
      birthday: new Date('1983-11-05'),
      personalInterests: ['humanitarian work', 'yoga', 'travel'],
      professionalGoals: ['digital health standards', 'pandemic preparedness tech'],
      painPoints: ['bureaucracy', 'funding cycles'],
      influenceLevel: 7,
      networkReach: 8,
      trustLevel: 3,
      loyaltyIndicator: 'likely' as const,
      financialCapacity: 'institutional' as const,
      motivations: ['global impact', 'equity'],
    },
    {
      id: contactIds.marco,
      userId: USER_ID,
      name: 'Marco Rossi',
      company: 'Ferrari',
      role: 'Head of Innovation Lab',
      city: 'Maranello',
      country: 'Italy',
      lat: 44.5327,
      lng: 10.8631,
      email: 'marco.rossi@ferrari.com',
      instagram: 'marco_rossi_it',
      tags: ['automotive', 'luxury', 'innovation'],
      notes: 'Runs Ferrari\'s secret innovation lab. Connected through Lena. Passionate about AI in manufacturing.',
      rating: 3,
      gender: 'male' as const,
      relationshipType: 'colleague' as const,
      metAt: 'CES 2025',
      metDate: new Date('2025-01-08'),
      lastContactedAt: daysAgo(15),
      communicationStyle: 'expressive' as const,
      preferredChannel: 'in-person' as const,
      responseSpeed: 'slow' as const,
      timezone: 'Europe/Rome',
      language: 'Italian',
      birthday: new Date('1979-04-18'),
      personalInterests: ['racing', 'wine', 'design'],
      professionalGoals: ['autonomous racing tech', 'smart factory'],
      painPoints: ['brand vs innovation tension', 'talent from Silicon Valley'],
      influenceLevel: 6,
      networkReach: 5,
      trustLevel: 2,
      loyaltyIndicator: 'neutral' as const,
      financialCapacity: 'institutional' as const,
      motivations: ['Italian excellence', 'future of mobility'],
    },
    {
      id: contactIds.anna,
      userId: USER_ID,
      name: 'Anna Kowalska',
      company: 'CD Projekt',
      role: 'Lead Game Designer',
      city: 'Warsaw',
      country: 'Poland',
      lat: 52.2297,
      lng: 21.0122,
      email: 'anna.k@cdprojekt.com',
      twitter: 'anna_gamedev',
      tags: ['gaming', 'creative', 'poland'],
      notes: 'Lead designer on Cyberpunk expansion. Creative genius. Good friend.',
      rating: 5,
      gender: 'female' as const,
      relationshipType: 'friend' as const,
      metAt: 'Gamescom 2023',
      metDate: new Date('2023-08-25'),
      lastContactedAt: daysAgo(5),
      nextFollowUp: futureDate(10),
      communicationStyle: 'direct' as const,
      preferredChannel: 'text' as const,
      responseSpeed: 'immediate' as const,
      timezone: 'Europe/Warsaw',
      language: 'Polish',
      birthday: futureDate(5),
      personalInterests: ['pen and paper RPG', 'pixel art', 'cats'],
      professionalGoals: ['creative director role', 'indie studio someday'],
      painPoints: ['crunch culture', 'publisher deadlines'],
      influenceLevel: 5,
      networkReach: 6,
      trustLevel: 5,
      loyaltyIndicator: 'proven' as const,
      financialCapacity: 'bootstrapper' as const,
      motivations: ['creative freedom', 'storytelling'],
    },
  ])

  const interactionData = [
    { contactId: contactIds.alex, type: 'meeting' as const, date: daysAgo(3), location: 'San Francisco', notes: 'Lunch at Blue Bottle. Discussed payments API integration.' },
    { contactId: contactIds.alex, type: 'call' as const, date: daysAgo(15), notes: 'Quick sync on the developer tools roadmap.' },
    { contactId: contactIds.alex, type: 'email' as const, date: daysAgo(30), notes: 'Shared our product deck. He forwarded to his team.' },
    { contactId: contactIds.alex, type: 'meeting' as const, date: daysAgo(60), location: 'Stripe HQ', notes: 'Office visit, met his team.' },
    { contactId: contactIds.maria, type: 'meeting' as const, date: daysAgo(12), location: 'Menlo Park', notes: 'Pitch meeting. She asked good questions about TAM.' },
    { contactId: contactIds.maria, type: 'email' as const, date: daysAgo(25), notes: 'Sent follow-up materials on market sizing.' },
    { contactId: contactIds.yuki, type: 'call' as const, date: daysAgo(45), notes: 'Discussed VR partnership opportunities.' },
    { contactId: contactIds.yuki, type: 'email' as const, date: daysAgo(50), notes: 'Sent proposal for spatial computing collab.' },
    { contactId: contactIds.omar, type: 'call' as const, date: daysAgo(20), notes: 'Caught up on MENA market. He offered intro to STC Ventures.' },
    { contactId: contactIds.omar, type: 'meeting' as const, date: daysAgo(40), location: 'Dubai', notes: 'Dinner at GITEX. Great conversations about mobility.' },
    { contactId: contactIds.sofia, type: 'email' as const, date: daysAgo(8), notes: 'Reviewed her paper draft on reasoning chains.' },
    { contactId: contactIds.sofia, type: 'meeting' as const, date: daysAgo(55), location: 'London', notes: 'Coffee at DeepMind campus. Fascinating discussion on AGI.' },
    { contactId: contactIds.james, type: 'call' as const, date: daysAgo(2), notes: 'He needs intros to EU compliance lawyers. I know someone.' },
    { contactId: contactIds.james, type: 'meeting' as const, date: daysAgo(10), location: 'Virtual', notes: 'Strategy session on pan-African expansion.' },
    { contactId: contactIds.james, type: 'call' as const, date: daysAgo(22), notes: 'Quick catch-up. Series D on track.' },
    { contactId: contactIds.james, type: 'email' as const, date: daysAgo(35), notes: 'Shared EU fintech regulation overview.' },
    { contactId: contactIds.lena, type: 'email' as const, date: daysAgo(60), notes: 'Birthday wishes. She mentioned new digital initiative at BMW.' },
    { contactId: contactIds.lena, type: 'meeting' as const, date: daysAgo(180), location: 'Munich', notes: 'Old friends dinner. She joined BMW recently.' },
    { contactId: contactIds.raj, type: 'call' as const, date: daysAgo(90), notes: 'Discussed SaaS metrics benchmarks.' },
    { contactId: contactIds.chen, type: 'email' as const, date: daysAgo(120), notes: 'He shared a paper on distributed training.' },
    { contactId: contactIds.fatima, type: 'meeting' as const, date: daysAgo(30), location: 'Geneva', notes: 'Met at WHO innovation showcase.' },
    { contactId: contactIds.marco, type: 'meeting' as const, date: daysAgo(15), location: 'CES Las Vegas', notes: 'Demo of their AI manufacturing prototype.' },
    { contactId: contactIds.anna, type: 'call' as const, date: daysAgo(5), notes: 'Gaming session + career chat. She is thinking about going indie.' },
    { contactId: contactIds.anna, type: 'meeting' as const, date: daysAgo(30), location: 'Warsaw', notes: 'Visited CD Projekt office. Amazing studio.' },
    { contactId: contactIds.anna, type: 'call' as const, date: daysAgo(14), notes: 'She playtested our VR prototype and gave great feedback.' },
  ]
  await db.insert(schema.interactions).values(interactionData)

  await db.insert(schema.contactConnections).values([
    { userId: USER_ID, sourceContactId: contactIds.alex, targetContactId: contactIds.maria, connectionType: 'introduced_by' as const, strength: 4, notes: 'Alex introduced me to Maria at TC Disrupt' },
    { userId: USER_ID, sourceContactId: contactIds.alex, targetContactId: contactIds.sofia, connectionType: 'works_with' as const, strength: 3, notes: 'Both on AI advisory board' },
    { userId: USER_ID, sourceContactId: contactIds.lena, targetContactId: contactIds.marco, connectionType: 'introduced_by' as const, strength: 3, notes: 'Lena introduced Marco at automotive conference' },
    { userId: USER_ID, sourceContactId: contactIds.omar, targetContactId: contactIds.james, connectionType: 'knows' as const, strength: 4, notes: 'Both in African/MENA fintech circles' },
    { userId: USER_ID, sourceContactId: contactIds.yuki, targetContactId: contactIds.anna, connectionType: 'works_with' as const, strength: 2, notes: 'Gaming industry overlap, met at TGS' },
    { userId: USER_ID, sourceContactId: contactIds.james, targetContactId: contactIds.alex, connectionType: 'knows' as const, strength: 3, notes: 'Connected them for payments infrastructure discussion' },
    { userId: USER_ID, sourceContactId: contactIds.maria, targetContactId: contactIds.james, connectionType: 'invested_in' as const, strength: 5, notes: 'Sequoia participated in Flutterwave round' },
    { userId: USER_ID, sourceContactId: contactIds.raj, targetContactId: contactIds.omar, connectionType: 'referred_by' as const, strength: 2, notes: 'Raj referred Omar for SaaS conference panel' },
    { userId: USER_ID, sourceContactId: contactIds.fatima, targetContactId: contactIds.sofia, connectionType: 'knows' as const, strength: 2, notes: 'Both interested in AI for health' },
    { userId: USER_ID, sourceContactId: contactIds.chen, targetContactId: contactIds.alex, connectionType: 'knows' as const, strength: 2, notes: 'Met at KubeCon, stayed in touch about infra' },
  ])

  await db.insert(schema.favors).values([
    { userId: USER_ID, contactId: contactIds.alex, direction: 'received' as const, type: 'introduction' as const, description: 'Introduced me to Maria Santos at Sequoia', value: 'critical' as const, status: 'active' as const, date: daysAgo(90) },
    { userId: USER_ID, contactId: contactIds.alex, direction: 'given' as const, type: 'advice' as const, description: 'Helped with his team reorg strategy', value: 'medium' as const, status: 'resolved' as const, date: daysAgo(60) },
    { userId: USER_ID, contactId: contactIds.james, direction: 'given' as const, type: 'introduction' as const, description: 'Introduced to EU compliance lawyers', value: 'high' as const, status: 'active' as const, date: daysAgo(2) },
    { userId: USER_ID, contactId: contactIds.james, direction: 'given' as const, type: 'resource' as const, description: 'Shared EU fintech regulation playbook', value: 'medium' as const, status: 'active' as const, date: daysAgo(35) },
    { userId: USER_ID, contactId: contactIds.raj, direction: 'given' as const, type: 'introduction' as const, description: 'Connected with Zoho leadership for partnership', value: 'high' as const, status: 'active' as const, date: daysAgo(180) },
    { userId: USER_ID, contactId: contactIds.omar, direction: 'received' as const, type: 'introduction' as const, description: 'Offered intro to STC Ventures', value: 'high' as const, status: 'active' as const, date: daysAgo(20) },
    { userId: USER_ID, contactId: contactIds.sofia, direction: 'given' as const, type: 'advice' as const, description: 'Reviewed her NeurIPS paper draft', value: 'medium' as const, status: 'active' as const, date: daysAgo(8) },
    { userId: USER_ID, contactId: contactIds.lena, direction: 'received' as const, type: 'introduction' as const, description: 'Introduced to Marco Rossi at Ferrari', value: 'high' as const, status: 'active' as const, date: daysAgo(45) },
    { userId: USER_ID, contactId: contactIds.anna, direction: 'received' as const, type: 'advice' as const, description: 'Playtested VR prototype, detailed feedback doc', value: 'medium' as const, status: 'active' as const, date: daysAgo(14) },
    { userId: USER_ID, contactId: contactIds.fatima, direction: 'given' as const, type: 'resource' as const, description: 'Shared health-tech market research', value: 'low' as const, status: 'active' as const, date: daysAgo(28) },
    { userId: USER_ID, contactId: contactIds.maria, direction: 'given' as const, type: 'opportunity' as const, description: 'Referred a promising AI startup for her pipeline', value: 'high' as const, status: 'active' as const, date: daysAgo(5) },
  ])

  await db.insert(schema.introductions).values([
    { userId: USER_ID, contactAId: contactIds.alex, contactBId: contactIds.maria, initiatedBy: 'contact_a', status: 'connected' as const, date: daysAgo(90), outcome: 'Led to pitch meeting and ongoing relationship', notes: 'Alex made warm intro at TC Disrupt' },
    { userId: USER_ID, contactAId: contactIds.lena, contactBId: contactIds.marco, initiatedBy: 'contact_a', status: 'connected' as const, date: daysAgo(45), outcome: 'Exploring automotive AI collab', notes: 'Lena connected us at CES' },
    { userId: USER_ID, contactAId: contactIds.james, contactBId: contactIds.omar, initiatedBy: 'you', status: 'connected' as const, date: daysAgo(30), outcome: 'They started discussing MENA-Africa payment corridor', notes: 'I connected them for fintech synergy' },
    { userId: USER_ID, contactAId: contactIds.sofia, contactBId: contactIds.fatima, initiatedBy: 'you', status: 'introduced' as const, date: daysAgo(7), notes: 'Connected them for AI-in-health collaboration' },
    { userId: USER_ID, contactAId: contactIds.raj, contactBId: contactIds.alex, initiatedBy: 'you', status: 'planned' as const, notes: 'Want to connect Raj with Alex for SaaS payments discussion' },
  ])

  await db.insert(schema.visitedCountries).values([
    { userId: USER_ID, country: 'United States' },
    { userId: USER_ID, country: 'Japan' },
    { userId: USER_ID, country: 'United Arab Emirates' },
    { userId: USER_ID, country: 'United Kingdom' },
    { userId: USER_ID, country: 'Germany' },
    { userId: USER_ID, country: 'India' },
    { userId: USER_ID, country: 'Nigeria' },
    { userId: USER_ID, country: 'Switzerland' },
    { userId: USER_ID, country: 'Italy' },
    { userId: USER_ID, country: 'Poland' },
    { userId: USER_ID, country: 'France' },
    { userId: USER_ID, country: 'Thailand' },
    { userId: USER_ID, country: 'Singapore' },
    { userId: USER_ID, country: 'South Korea' },
    { userId: USER_ID, country: 'Brazil' },
  ])

  console.log('Seed complete: 12 contacts, 25 interactions, 10 connections, 11 favors, 5 introductions, 15 visited countries')
  await pool.end()
}

seed().catch(console.error)
